### ISSUE TITLE
Register OAuth2AuthorizedClientArgumentResolver for XML Config

### ISSUE THREAD

**Issue by realulim** [spring-projects/spring-security#8669]
**Describe the bug**
Normally, when oauth2-login is configured, it is possible to inject @AuthenticationPrincipal and @RegisteredOAuth2AuthorizedClient into controller methods. The former always works, the latter only with Java configuration. With an XML configuration like this:
```
        <sec:http pattern="/my-api/**" use-expressions="true" auto-config="false">
            <sec:csrf disabled="true"/>
            <sec:intercept-url pattern="/my-api/**" access="authenticated"/>
            <sec:oauth2-login access-token-response-client-ref="accessTokenResponseClient"/>
        </sec:http>
...
        <sec:client-registrations>
            <sec:client-registration registration-id="myId" ... />
            <sec:provider provider-id="myProvider" .../>
        </sec:client-registrations>
```
And controller code like this:
```
    public Map<String, Object> getStuff(
            @AuthenticationPrincipal Principal principal,
            @RegisteredOAuth2AuthorizedClient(registrationId = "myId") OAuth2AuthorizedClient client) {
...
}
```
I am getting the following stacktrace:

>  | Caused by: java.lang.IllegalStateException: No primary or default constructor found for class org.springframework.security.oauth2.client.OAuth2AuthorizedClient
>  |         at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:219)
>  |         at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.createAttribute(ServletModelAttributeMethodProcessor.java:85)
> ...
> Caused by: java.lang.NoSuchMethodException: org.springframework.security.oauth2.client.OAuth2AuthorizedClient.<init>()
>  |         at java.lang.Class.getConstructor0(Class.java:3082)

With the equivalent configuration in Java it works. There might be a problem with the client registrations being an inner bean and somehow not getting managed properly in the OAuth2AuthorizedClientRepository.

**Comment by jgrandja** [comment]
Thanks for the report @realulim.

The Java configuration registers `OAuth2ClientConfiguration.OAuth2ClientWebMvcSecurityConfiguration` and adds `OAuth2AuthorizedClientArgumentResolver`, which resolves `OAuth2AuthorizedClient` via `@RegisteredOAuth2AuthorizedClient`.

The issue is that `OAuth2AuthorizedClientArgumentResolver` is not automatically registered when using XML config.

I'll add this to our backlog as an enhancement.

**Comment by realulim** [comment]
Thank you for confirming and taking it on. As a workaround, would it be somehow possible to manually configure the OAuth2AuthorizedClientArgumentResolver?

**Comment by jgrandja** [comment]
@realulim I just pushed this enhancement to master. Let me know how it goes.

**Comment by realulim** [comment]
I checked out master and did ./gradlew install and ./gradlew build, but the generated jar in build/libs has no classes. Is there a place where binaries could be downloaded, perhaps a nightly build?

**Comment by jgrandja** [comment]
@realulim You'll need to test this against the snapshot repository https://repo.spring.io/snapshot.
See the [reference doc](https://docs.spring.io/spring-security/site/docs/5.3.3.BUILD-SNAPSHOT/reference/html5/#maven-repositories) for maven configuration.

**Comment by jgrandja** [comment]
@realulim The Spring versioning scheme changed recently - see [announcement](https://spring.io/blog/2020/04/30/updates-to-spring-versions).

Instead of `5.4.0.BUILD-SNAPSHOT` use the new tag `5.4.0-SNAPSHOT`.

Here is a working [sample](https://github.com/jgrandja/oauth2login-demo/tree/xml-config) (xml-config branch) for your reference.

**Comment by realulim** [comment]
I am still getting the same exception. My configuration is very similar to the example, only that I am using an external authorisation server and thus need a custom AccessTokenClient. I suppose at this point I need to create a minimal example to reproduce the error.

```
| Caused by: java.lang.NoSuchMethodException: org.springframework.security.oauth2.client.OAuth2AuthorizedClient.<init>()
|         at java.lang.Class.getConstructor0(Class.java:3082)
|         at java.lang.Class.getDeclaredConstructor(Class.java:2178)
|         at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:216)
|         ... 149 more

```

**Comment by jgrandja** [comment]
Yes, please put together a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.
